sudo: required

language: java

jdk: openjdk8

cache:
  directories: 
    - WS245

services:
  - docker

install:
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  - cd ${TRAVIS_BUILD_DIR}
  - docker pull andersenlab/nil-ril-nf

  
script: "./test.sh"

notifications:
  email: true