sudo: required

language: java

jdk: openjdk8

services:
  - docker

install:
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  - ls ${TRAVIS_BUILD_DIR}
  - cd ${TRAVIS_BUILD_DIR}/${TRAVIS_REPO_SLUG}

script: "test.sh"